### PR TITLE
Python CLI

### PR DESCRIPTION
**Pull request by austinhuang0131**
eg. `./main.py -f input/*.c`. Options are provided to specify what patches to run on and what options to be passed to `spatch`, except `--python` which is handled by the program.

### CODE REVIEW

**Comment by FNZhao** [comment]
- Running patches against multiple files and folders is needed.

- The message `usage: atom-finder-coccinelle [-h] [-p [PATCH ...]] [-o ...] file` is confusing to me. Is `file` a positional argument? I was able to run `atom-finder-coccinelle comma_operator.cocci -p input/comma_operator.c`, but `atom-finder-coccinelle input/comma_operator.c -p comma_operator.cocci` failed.

**Comment by austinhuang0131** [comment]
* Ah, okay, I will work on that.
* Yes, `file` is positional; line 11. But `-p` is for `.cocci` patches, so you should not be able to run either command (in your first command the program will treat `input/comma_operator.c` as a patch). I suppose that is a fault in `argparse` though.

Anyways, now that we have multiple input files, I will make `file` a required option instead.

**Comment by FNZhao** [comment]
Sorry I'm not familiar with CLI. I tried to modify the usage message but couldn't find where it was generated.

**Comment by austinhuang0131** [comment]
`argparse` generates the help message based on arguments supplied; see https://docs.python.org/3/library/argparse.html#example . In this case the arguments are defined as

https://github.com/AtomsofConfusion/atom-finder-coccinelle/blob/c793c7b173063c5c35ee36e672375dec70ff7354/main.py#L8-L17

So it seems that `argparse` always put positional arguments at the end for help messages. But if I'm to make it an option then it's not really relevant now...

**Comment by austinhuang0131** [comment]
```
$ atom-finder-coccinelle -h
usage: atom-finder-coccinelle [-h] [-f [FILE ...]] [-p [PATCH ...]] [-o ...]

Apply coccinelle patches onto C files

options:
  -h, --help            show this help message and exit
  -f [FILE ...], --file [FILE ...]
                        List of C files to run patches on, separated by spaces. If not specified, all *.c files in the current
                        directory will be run.
  -p [PATCH ...], --patch [PATCH ...]
                        List of coccinelle patches to run, separated by spaces. If not specified, all *.cocci files in the current
                        directory will be run.
  -o ..., --opts ...    Options to pass to `spatch`
  ```

**Comment by FNZhao** [comment]
Is it possible to run patches against a folder, such as the input folder?

**Comment by austinhuang0131** [comment]
Yes, eg. `atom-finder-coccinelle -f input/*.c`.

**Comment by renatav** [comment]
@austinhuang0131 Thank you for the contribution! Could we rename the parameter to `--input` or `-i` and add support for both files and directories? `spatch` already allows you to run a patch against a directory, without having to use globs.

**Comment by austinhuang0131** [comment]
I have modified the parameter.

1. Should directories be accepted in `--patch`/`-p`?
2. It should be noted that `spatch` does try to find C files in the subdirectories as well. So currently one can just do `./main.py` and everything in the directory will be run, but it wouldn't if the cocci files are in a subdirectory. Should `--patch`/`-p` also find files in the subdirectories of the specified directories?

**Comment by FNZhao** [comment]
The second one should be implemented, and it would be great if we could do both.

**Comment by austinhuang0131** [comment]
It is done. Generally I don't want to bother y'all too much (emails...), so I try to consolidate my pushes and not write a comment, but in the absence of other communication channels I suppose it is necessary...

In the current folder structure, one can just run `./main.py` in it without any arguments. It will still work if the cocci files are moved to a different folder in the repository.

To summarize the current changes: if any directory is supplied in either `-i` or `-p`, then it will traverse all of its subdirectories as well. ie. `-p folder` is the same as `-p folder/**/*.cocci`. `-i` is handled by `spatch`; `-p` is handled by the script.

**Review by renatav — APPROVED** [review]
Merging this in. The code looks good for the most part. There is no need for it to be on the fork. If there are any issues, we can fix in a separate PR

**Pull request merged**
